### ISSUE TITLE
write HorizontalMenu

### ISSUE THREAD

**Issue by chistopher** [chistopher/schnaxen#5]
change keybindings of app and battle to add all keybindings of their menus instead of writing them down.

**Comment by chistopher** [comment]
app uses subwindow to display its menu so the menu has its own keybindings

**Comment by chistopher** [comment]
menus should clip submorphs and if there are less items than visibleItems center them.
visibleitems may change?

**Comment by chistopher** [comment]
refactoring https://github.com/chistopher/schnaxen/commit/79fe50c654391bd3a6eed3dc060c3d76c555bff5

**Comment by MultifokalHirn** [comment]
hi süßer bock auf ne flotte Nummer?
